routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostController::class, 'index']);

Route::resource('posts', PostController::class);
Route::resource('comments', CommentController::class)->except('index');
Route::resource('users', UserController::class)->only('show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::put('posts/{post}/approve', [PostController::class, 'approve'])->name('posts.approve');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['body', 'publication_date', 'user_id', 'category_id'];

    /**
     * @return HasMany
     */
    public function tags(): HasMany
    {
        return $this->hasMany(Tag::class);
    }

    /**
     * @return HasMany
     */
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return BelongsTo
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->BelongsTo(User::class);
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Models\Category;
use App\Models\Post;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $posts = Post::paginate(8);
        $current_date = Carbon::now();
        return view('posts.index', compact('posts', 'current_date'));
    }


    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.create', compact('categories', 'tags'));
    }


    /**
     * @param PostRequest $request
     * @return RedirectResponse
     */
    public function store(PostRequest $request): RedirectResponse
    {
        $post = new Post();
        $post->body = $request->input('body');
        $post->category_id = $request->input('category_id');
        $post->user_id = auth()->user()->id;
        $post->tag_1 = $request->input('tag_1');
        $post->tag_2 = $request->input('tag_2');
        $post->tag_3 = $request->input('tag_3');
        $post->save();
        return redirect()->route('posts.index')->with('status', "Post successfully created!");
    }


    /**
     * @param Post $post
     * @return Application|Factory|View
     */
    public function show(Post $post)
    {
        return view('posts.show', compact('post'));
    }


    /**
     * @param Post $post
     * @return Application|Factory|View
     */
    public function edit(Post $post)
    {
        $this->authorize('update', $post);
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.edit', compact('post','categories', 'tags'));
    }


    /**
     * @param Post $post
     * @param Request $request
     * @return RedirectResponse
     */
    public function update(Post $post, PostRequest $request): RedirectResponse
    {
        $this->authorize('update', $post);
        $post->body = $request->input('body');
        $post->tag_1 = $request->input('tag_1');
        $post->tag_2 = $request->input('tag_2');
        $post->tag_3 = $request->input('tag_3');
        $post->update();
        return redirect()->route('posts.index')->with('status', "Post successfully created!");
    }

    /**
     * @param Post $post
     * @param Request $request
     * @return RedirectResponse
     */
    public function approve(Post $post, Request $request): RedirectResponse
    {
        $post->publication_date = $request->input('publication_date');
        $post->save();
        return redirect()->route('posts.index')->with('status', "Post successfully created!");
    }
    /**
     * @param Post $post
     * @return RedirectResponse
     */
    public function destroy(Post $post): RedirectResponse
    {
        $this->authorize('delete', $post);
        $post->delete();
        return redirect()->route('posts.index')->with('status', "Post successfully deleted!");
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Create new post</h1>
        <form enctype="multipart/form-data" method="post" action="{{ route('posts.store') }}">
            @csrf
            <div class="form-group">
                <label for="body">Body</label>
                <textarea class="form-control @error('body') is-invalid @enderror" id="body"
                          name="body"></textarea>
                @error('body')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
            </div>
            <div class="form-group">
                <label for="category_id">Choose category</label>
                <select class="custom-select" name="category_id">
                    @foreach($categories as $category)
                        <option value="{{$category->id}}">{{$category->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="tag_1">Choose tag</label>
                <select class="custom-select" name="tag_1">
                    <option value="">Open this select menu</option>
                @foreach($tags as $tag)
                        <option value="{{$tag->name}}">{{$tag->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="tag_2">Choose tag</label>
                <select class="custom-select" name="tag_2">
                    <option value="">Open this select menu</option>
                @foreach($tags as $tag)
                        <option value="{{$tag->name}}">{{$tag->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="tag_3">Choose tag</label>
                <select class="custom-select" name="tag_3">
                    <option value="">Open this select menu</option>
                @foreach($tags as $tag)
                        <option value="{{$tag->name}}">{{$tag->name}}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
    <h1>Edit post</h1>
    <form enctype="multipart/form-data" method="post" action="{{ route('posts.update', ['post' => $post]) }}">
        @method('put')
        @csrf
        <div class="form-group">
            <label for="body">Body</label>
            <textarea class="form-control @error('body') is-invalid @enderror" id="body"
                      name="body">{{$post->body}}</textarea>
            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="category_id">Category</label>
            <select class="custom-select" name="category_id">
            @foreach($categories as $category)
                    <option value="{{$category->id}}" @if($category == $post->category) selected @endif>{{$category->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="tag_1">Choose tag</label>
            <select class="custom-select" id="tag_3" name="tag_1">
                <option value="">Open this select menu</option>
            @foreach($tags as $tag)
                    <option value="{{$tag->name}}">{{$tag->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="tag_2">Choose tag</label>
            <select class="custom-select" id="tag_3" name="tag_2">
                <option value="">Open this select menu</option>
            @foreach($tags as $tag)
                    <option value="{{$tag->name}}">{{$tag->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="tag_3">Choose tag</label>
            <select class="custom-select" id="tag_3" name="tag_3">
                <option value="">Open this select menu</option>
            @foreach($tags as $tag)
                    <option value="{{$tag->name}}">{{$tag->name}}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Обновить</button>
    </form>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div style="padding-bottom: 30px;">
            <h3>Posts</h3>
        </div>
        @if(Auth::check())
        <a href="{{route('posts.create')}}" type="button" class="btn btn-outline-primary">
            Create post
        </a>
        @endif
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Body</th>
                <th scope="col">Author</th>
                <th scope="col">Date of creation</th>
                <th scope="col">Date of publication</th>
                <th scope="col">Category</th>
                <th scope="col">Tags</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            @foreach($posts as $post)
                @if($post->publication_date != '')
                    @if($current_date->lt($post->publication_date))
                        <tbody>
                        <tr>
                            <td>{{$post->body}}</td>
                            <td><a href="{{route('users.show', ['user' => $post->user])}}"
                                   class="btn btn-link">{{$post->user->name}}</a></td>
                            <td>{{$post->created_at}}</td>
                            <td>{{$post->publication_date}}</td>
                            <td>{{$post->category->name}}</td>
                            <td>{{$post->tag_1}} {{$post->tag_2}} {{$post->tag_3}}</td>
                            <td><a href="{{route('posts.show', ['post' => $post])}}" class="btn btn-primary">Show</a>
                                @can('update', $post)
                                    <a class="btn btn-outline-primary"
                                       href="{{route('posts.edit', ['post' => $post])}}">
                                        Edit
                                    </a>
                                @endcan
                                @can('update', $post)
                                    <form method="post" action="{{route('posts.destroy', ['post' => $post])}}">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-outline-danger">Delete</button>
                                    </form>
                                @endcan
                            </td>
                        </tr>
                        </tbody>
                    @endif
                @else
                    @if(auth()->check())
                        @if(auth()->user()->is_admin)
                            <tr>
                                <td>{{$post->body}}</td>
                                <td><a href="{{route('users.show', ['user' => $post->user])}}"
                                       class="btn btn-link">{{$post->user->name}}</a></td>
                                <td>{{$post->created_at}}</td>
                                <td>@if($post->publication_date)
                                        {{$post->publication_date}}
                                    @else
                                        Not published
                                    @endif
                                </td>
                                <td>{{$post->category->name}}</td>
                                <td>{{$post->tag_1}} {{$post->tag_2}} {{$post->tag_3}}</td>
                                <td><a href="{{route('posts.show', ['post' => $post])}}"
                                       class="btn btn-primary">Show</a>
                                    @can('update', $post)
                                        <a class="btn btn-outline-primary"
                                           href="{{route('posts.edit', ['post' => $post])}}">
                                            Edit
                                        </a>
                                    @endcan
                                    @can('update', $post)
                                        <form method="post" action="{{route('posts.destroy', ['post' => $post])}}">
                                            @method('delete')
                                            @csrf
                                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                                        </form>
                                    @endcan
                                    <form method="post" action="{{route('posts.approve', ['post' => $post])}}">
                                        @method('put')
                                        @csrf
                                        <input type="date" name="publication_date" id="publication_date">
                                        <input name="post_id" type="hidden" id="post_id" value="{{$post->id}}">
                                        <button type="submit" class="btn btn-success">Approve</button>
                                    </form>
                                </td>
                            </tr>
                        @endif
                    @endif
                @endif
            @endforeach
        </table>
    </div>
    <div class="row justify-content-md-center p-5">
        <div class="col-md-auto">
            {{ $posts->links('pagination::bootstrap-4') }}
        </div>
    </div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="border-bottom pb-3 mb-3">
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-2 .img-fluid. w-100%  h-auto ">
                <div class="col mb-4">
                    <br>
                    <p>{{$post->body}}</p>
                </div>
                <footer class="blockquote-footer">
                    Author: {{$post->user->name}}, created in
                    <cite title="Created at article">
                        {{$post->created_at->diffForHumans()}}
                    </cite>
                </footer>
            </div>
        </div>
        @if(Auth::check())
            <form method="post" action="{{route('comments.store', ['post' => $post])}}">
                @csrf
                <input type="hidden" id="post_id" value="{{$post->id}}">
                <label for="satisfied"><strong>satisfied:</strong></label>
                <select name="satisfied" id="satisfied">
                    <option value="1">Yes</option>
                    <option value="0">No</option>
                </select>
                <label for="quality"><strong>quality:</strong></label>
                <select name="quality" id="quality">
                    <option value="1">Yes</option>
                    <option value="0">No</option>
                </select>
                <label for="actuality"><strong>actuality:</strong></label>
                <select name="actuality" id="actuality">
                    <option value="1">Yes</option>
                    <option value="0">No</option>
                </select>
                <div class="form-group">
                    <label for="body">Body</label>
                    <textarea class="form-control @error('body') is-invalid @enderror" id="body"
                              name="body"></textarea>
                    @error('body')
                    <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        @endif
        <div class="row">
            <div class="col-8 scrollit">
                @foreach($post->comments as $comment)
                    <br>
                    @include('comments.comment', ['comment' => $comment])
                @endforeach
            </div>
        </div>
@endsection