routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostController::class, 'index']);

Route::resource('posts', PostController::class);
Route::resource('comments', CommentController::class)->except('index');
Route::resource('users', UserController::class)->only('show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::put('posts/{post}/approve', [PostController::class, 'approve'])->name('posts.approve');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'body', 'quality', 'actuality', 'satisfied', 'post_id'];

    /**
     * @return BelongsTo
     */
    public function post(): BelongsTo
    {
        return $this->belongsTo(Post::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Models\Post;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * @param Request $request
     * @param Post $post
     * @return RedirectResponse
     */
    public function store(Request $request, Post $post): RedirectResponse
    {
        $request->validate([
            'body' => 'required|min:5',
            'quality' => 'required',
            'actuality' => 'required',
            'satisfied' => 'required',
        ]);
        $comment = new Comment();
        $comment->user_id = $request->user()->id;
        $comment->body = $request->input('body');
        $comment->quality = $request->input('quality');
        $comment->actuality = $request->input('actuality');
        $comment->satisfied = $request->input('satisfied');
        $comment->post_id = $post->id;
        $comment->save();
        return redirect()->route('posts.show', $comment->post_id);
    }

    /**
     * @param Comment $comment
     * @return RedirectResponse
     */
    public function destroy(Comment $comment): RedirectResponse
    {
        $this->authorize('delete', $comment);
        $comment->delete();
        return redirect()->route('posts.show', $comment->post_id);
    }
}

resources/views/comments/comment.blade.php
<div class="container">
    <div class="media g-mb-30 media-comment">
        <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
            <div class="g-mb-15">
                @can('delete', $comment)
                    <form method="post" action="{{route('comments.destroy', ['comment' => $comment])}}">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                @endcan
                <h4 class="h5 g-color-gray-dark-v1 mb-0">Satisfied:{{$comment->satisfied}}</h4>
                    <h4 class="h5 g-color-gray-dark-v1 mb-0">Quality:{{$comment->quality}}</h4>
                    <h4 class="h5 g-color-gray-dark-v1 mb-0">Actuality:{{$comment->actuality}}</h4>
                    <h5 class="h5 g-color-gray-dark-v1 mb-0">{{$comment->user->name}}</h5>
                <span class="g-color-gray-dark-v4 g-font-size-12">{{$comment->created_at->diffForHumans()}}</span>
            </div>
            <p>
                {{$comment->body}}
            </p>
        </div>
    </div>
</div>